### ISSUE TITLE
Autocomplete search

### ISSUE THREAD

**Issue by eightysteele** [VertNet/webapp#242]
We're using Google Bigtable for storage which performs very well at scale. But the tradeoff is that it doesn't support queries requiring a full index scan, so type-ahead autocomplete stuff isn't possible. For advanced search we could query specialized views in CartoDB via standard SQL, so we can definitely "fake it" in some cases.

**Comment by laurarussell** [comment]
Is this possible now with more recent Google changes and changes to the index or should this be marked as wontfix and closed?

**Comment by tucotuco** [comment]
Closing.
