### ISSUE TITLE
DayOfYear search

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#270]
To cover queries that depend on any kind of time during a year, we need to enable "seasonal" querying based on Darwin Core's two day of year fields.

If there is a desire for date range queries (verydifferent beast), a new issue should be submitted for that.

For this one, the things to solve are how to index and do a range query on a concept that is itself a range. Has many philosophical similarites to a spatial query, where overlap is a fundamental issue. Needs a theoretical framework before writing code.

**Comment by laurarussell** [comment]
This this is addressed by new DwC terms added to index. And changes that will be made to month, day, year fields on Advanced?  @tucotuco do concur?

**Comment by tucotuco** [comment]
startdayofyear and enddayofyear are not indexed in the new schema. :-( It must remain a to do for some day.

**Comment by tucotuco** [comment]
Added in post-harvest-processor in commit 199ce7398ab2890ada701f712a7e6b6db4b431ae
