### ISSUE TITLE
Links from the main search table are broken in Opera

### ISSUE THREAD

**Issue by gaurav** [VertNet/webapp#272]
For me, I'm getting URLs which look like this when I do a search on the main search table: http://wip.vertnet-portal.appspot.com/search/undefined/museum-of-vertebrate-zoology-uc-berkeley/mvz-egg-and-nest-collection-arctos?id=5e515969-6d5b-414b-a629-c72eedfcc95d&view=darwincore

I get these URLs whatever search string I use on both the front page and the search page on Opera 12.16 on MacOS X. I don't see this problem in Firefox.

If I remove the "search/undefined" bit from the URL, the URL works fine.

**Comment by laurarussell** [comment]
@gaurav is this still an issue for you?

**Comment by gaurav** [comment]
Searching now works fine for me on Opera 30.0. Closing.
