### ISSUE TITLE
Better zoom on map (all instances)

### ISSUE THREAD

**Issue by mkoo** [VertNet/webapp#305]
Better control on where to zoom, which can be implemented in a various way (whatever works, no strong preference at the moment)

One option--Drag 'n' Zoom as Map Labs has in google maps: toggle button to draw a box on the map, and zoom! You're there!

Another-- GeoLocate allows holding down Shift key and mouse-dragging to draw box and zoom

perhaps a Right-click for drag/draw a zoom box.

**Comment by tucotuco** [comment]
The zoom behavior on the map is the default for Google Maps.
