### ISSUE TITLE
Add "Load All" button to the map

### ISSUE THREAD

**Issue by atrox10** [VertNet/webapp#327]
When someone is looking at the map view, you can only see some of the records, and when you hit the "Load More" button, you still cannot see all the records from the search. This is very confusing for people searching, because they think that there are records missing from the map and don't realize that everything isn't loaded (this is what happened when I showed the mapping view to Ted Papenfuss). We need a "Load All" button!!!

**Comment by laurarussell** [comment]
The download counts is detailed in issue #376.  And we know there is no way to have a load all button.  Marking this one as won't fix.
