### ISSUE TITLE
Publisher  resources

### ISSUE THREAD

**Issue by robgur** [VertNet/webapp#329]
I am not sure that showing the number of "resources" helps the user a whole lot.  If one could rollover the number of resources and get their names, that might be useful.  Without more context, I doubt the resource #s do a whole lot of good -- may as well save the real estate. 

Having said that, IF the resource labels could be shown somehow from the publisher page, that _is_ useful.

There is probably more to do with publisher and resource contents.  It would be nice to get the data rights stuff for each resource by clicking through publisher to resource but I think this is probably something for V0.0.5 and not for the public release beta (which I think is 0.0.4)

**Comment by laurarussell** [comment]
This has been resolved over time.
