### ISSUE TITLE
metadata search advanced option

### ISSUE THREAD

**Issue by eightysteele** [VertNet/webapp#354]
we only fulltext index dwc terms. add advanced search support for fulltext searching metadata (e.g., resource description, rights, citation) as a checkbox.

**Comment by laurarussell** [comment]
This was marked as a priority? Do we really need a check box on advanced search to search meta data?  We have recently discussed search CC0.  Needs more discussion or mark this as wontfix and add a new issue for searching CC0.

**Comment by tucotuco** [comment]
Added both license and iptlicense to the search capabilities, among a host of others.
