### ISSUE TITLE
Improperly parsed records for very long occurrenceRemarks

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#359]
Javier reported...

"http://portal.vertnet.org/o/macaulay-library/macaulay-library-audio-and-video-collection?id=c084d0aa-59cf-4aaa-b9a0-363a2ccae389#allterms

Scroll down and you'll see..."

Well, looking back through the history of the migration process, the record is actually fine. The issue seems to be that the comment exceeds the length expectations somewhere further down in the process. The field content is broken after 39107 characters of occurrenceRemarks, where the total length of the original, a transcript of the conversation on the sound recording, is 52669 characters. There are no control characters or anything else funky in the original at that location. Everything after that in the record on the portal looks like a consequence of the first problem.

There is more to research, because there are 125 records in that data source that potentially could be affected if length alone is an issue.

**Comment by laurarussell** [comment]
Seems resolved with new index deployment or perhaps John remigrated.  I can't find any now that are overflowing in the details view.  @tucotuco  can you verify if you changed something to fix this so we can close it?

**Comment by tucotuco** [comment]
These all work fine now. Example:

http://portal.vertnet.org/o/cuml/sound?id=film/163440
