### ISSUE TITLE
Display more fields/Select fields for display in search results

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#360]
From Janet Hinshaw, U of Michigan, jhinshaw@umich.edu

Please give us your feedback. Please use as much detail as necessary. Is there a way to get more fields displayed in the search results? There aren't enough, you should be able to choose more fields. I liked the search portal for Ornis much better as it would display all the fields and if you were looking for something like collector number it was easy to scroll down the page. Having to open each entry to see the other fields is just not workable. I know we mapped collector number etc. so why isn't it showing up?

**Comment by laurarussell** [comment]
Added recordedBy, sex, and full date to search results display.

**Comment by laurarussell** [comment]
Fixed by #563
