### ISSUE TITLE
Order of processes - Harvest and Meta Data Refresh

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#362]
When doing a harvest and meta data refresh for publishers list, the publishers list, http://portal.vertnet.org/publishers, should not be refreshed until the harvest is complete and indexed data is available in the portal.  

Right now, we have two new publishers in the publishers list whose data has not yet been harvested/indexed and as such their data is not yet searchable in the portal. (I know the last harvest/index which included these failed).  I will remove them from the resource table in CartoDB once this is acknowledged.

http://portal.vertnet.org/p/danish-centre-for-environment-and-energy

http://portal.vertnet.org/p/zoological-museum-natural-history-museum-of-denmark

**Comment by laurarussell** [comment]
This may belong in gulo?  Also, maybe a wontfix at this point.

**Comment by tucotuco** [comment]
We control publisher visibility in the portal publishers list entirely by
CartoDB. No action necessary.
