### ISSUE TITLE
Send query results to multiple users

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#365]
Our illustrious leader has asked if we can send the downloaded query results to more than one user at a time.  Seems like a useful addition.  My question is how do you handle d/ls of <1000 records?  Stuff to think about.

**Comment by laurarussell** [comment]
Seems like this is a wontfix?

**Comment by tucotuco** [comment]
Closing issue. User can share the URL of the query, or forward the email announcing the results have been created and are ready for download.
