### ISSUE TITLE
Surface country and state in query_log

### ISSUE THREAD

**Issue by jotegui** [VertNet/webapp#369]
Would it be possible to add these two fields to the data logged in cartodb query_log table? Thus, we could extract queries and downloads per country/state

**Comment by laurarussell** [comment]
@jotegui is this still an open issue?

**Comment by jotegui** [comment]
It's semi-workaround-ed. Country is being inferred from latlon using
Geonames, which is not too efficient but was an Q&D fix. Country could be
easily extracted from headers (I think), but it would need some testing on
the stats generator side to make sure it doesn't break anything. If
processing time is not an issue (which I think is the case since it runs in
the background), I'd say keep it as it is and close this issue. State is
not being surfaced, but I'm not really sure I see the point in it, so IMHO,
I'd say this is a wontfix...

Any of you guys against leaving it as it is?

Javier Otegui
http://about.me/jotegui

**Comment by tucotuco** [comment]
Agreed.
