### ISSUE TITLE
Search d/l's not being returned.

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#376]
Aaron, Javi,

I've been working with Steve Rogers at CM to help him with his issues related to the Virginia/West Virginia search noted in another issue.

In addition I've been trying to d/l this set of search results for him with no luck.  I've tried twice, once today and once yesterday (I have asked Laura to try today too - so far, nothing has been returned).  The query is http://portal.vertnet.org/search?q=stateprovince:Virginia+AND+NOT+West+institutioncode:CM

I have visited our download page on Google Cloud and I see both of my requests there (both start with CM_).  When I d/l'd those from Google, they were clearly incomplete.  One had only 22 records, the other only 44.  I guessing, based on the estimated records provided by the portal that there should have been at least 40 or 50 thousand records in each.

This is a bit time sensitive as I would like to provide Steve with some query results when I follow up with him.

d

**Comment by laurarussell** [comment]
Need confirmation that this is resolved so it can be closed.

**Comment by tucotuco** [comment]
This seems to be resolved with the refactoring to remove dependency on the Files API. Tested the query and got a download of 19644 records in just under 5 minutes.
