### ISSUE TITLE
Feeback on APIs (function and documentation)

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#382]
Initial feedback from Joyce and Dusty below:

JOYCE:

It looks as if the API is not working now? See errors below.

I can't really comment on the documentation unless I can try it out. It looks as if the API would work for what AmphibiaWeb needs (download tab-delimited file of all Amphibia; search for species by lat/long), but I can't be sure without seeing some results.

Joyce

Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~vertnet-portal/api.371343770297424871/vertnet/service/api.py", line 35, in get
    request = json.loads(self.request.get('q'))
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 6 (char 5)

DUSTY:

Hi Dave - sorry I'm a little late with this - I hope it's useful anyway.

"TTP and is accessed from the api.vertnet-portal.appspot.com domain. "

Not admitting a lack of reading comprehension here or anything, but it took me forever to find that - and then I have to copypaste everything. Working example links should be considered absolutely mandatory. I would bet that I've missed great products because of no example links - I don't care what you THINK it does, I want to SEE what it does. And to extend that, if I'm evaluating some product and it says "click here to turn things blue!" and clicking actually turns everything red, I'm out. I'll deal with crappy documentation if I have to, but I'll never willingly deal with unpredictable software. More below....

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22distance%28location,geopoint%2837.2,-122%29%29%3C1000%20class:aves%22}

gives me

{"count": 0, "cursor": null, "recs": []}

On things that do work, why is everything count: -1 ?

"count": "-1"

also wuts 

"dummy": ";\n"

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22mvz%20bird%20california%22}

Please try again. Error: Timeout

Smash reload enough and I get a bunch of remarks....

STOMACH FULL OF 18CM ANCHOVIES. SEGMENTED WORMS.  Partial skeleton,
 wing, and frozen tissues at the Museum of Vertebrate Zoology (MVZ 
172440). 

...but no MVZ birds

I still can't get the thing to send me email. I'm not sure I've ever got one of the dozens or hundreds of emails I've requested from vertnet. If that doesn't exist, can you remove the links? If it is supposed to exist - well, it kinda doesn't.

The javascript feedback example is just confusing/strange - what if I don't want to use JS?? Again, a working link example would be awesome.

I don't think the

Field keyword search

Year
Genus
InstitutionCode
Country
StateProvince
County
SpecificEpithet
CatalogNumber
CollectorName
Class

works.

 

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22Genus:mus%22}

returns

: "Found dead.  Stomach contained Mus musculus (in separate vial).", 

and

1 mi. East of Stan. Nat. Hist. Mus. near Convalescent Home - 100 yds. of San Francisquito Cr., Santa Clara Co., Cal.

and everything else under the sun - except mice (they're probably in there somewhere....)

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22StateProvince:%20mus%22}

seems to return the same thing.

Sorry, I think I wandered off to left field again. I'm not sure that it's the API documentation that's the problem. As far as API documentation goes, if there were some working links, and if it's complete, it's acceptable. I can figure out what I think it's supposed to do, it seems to return valid json, etc.

It's hard to document things that don't work, and I maintain that at this point vertnet does not work.

Fix please....

**Comment by tucotuco** [comment]
Much of this has been resolved. Can someone test thoroughly and see if any of these reported issues remains?

**Comment by tucotuco** [comment]
I have tested all of the issues raised here and found them all to be resolved following the refactoring to remove the Files API dependency.
