### ISSUE TITLE
Tabs in data records will cause trouble

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#391]
Indexing assumes well-formatted tab-delimited input. Records having tabs in the data content are going to produce errors.

https://github.com/VertNet/webapp/blob/feature/index/vertnet/service/search.py#L299

**Comment by laurarussell** [comment]
Is this something to be fixed? Or can this be closed?

**Comment by tucotuco** [comment]
This was anticipation, but I have never seen it cause trouble to date. Closing.
