### ISSUE TITLE
Search for term in dwc:preparations and Advanced search fields returns unexpected records without search term.

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#422]
It begins with this user feedback:

Question                 Answer
First Name               Nancy
Last Name                Moncrief
Email Address            nancy.moncrief@vmnh.virginia.gov
What would you like to tell us about (select one)?               Portal/web site issues
Let us know how we can get you started (select one):
Institution or Collection Name
Please give us your feedback, ask your question, or describe your issue. Use as much detail as necessary. You can attach a screen capture and other documentation in the next field below.               
"I am trying to locate specimens that include post-cranial elements of 2 species of tree squirrels (Sciurus niger and S. carolinensis).  In MANIS, I was able to select "skeleton only" as a preparation type.

Which terms, in which fields on the VertNet portal, should I use to retrieve these data in VertNet?

"skeleton only"  as exact phrase retrieves no records

when I put "skeleton"  as includes, the search brings up records with the word "skeleton" in the occurence notes field of many records, but not as a preparation type."

COMMENTS:

When attempting to recreate this issue I tested both S. niger and S. carolinensis with several combinations of terms including examples such as [Sciurus carolinensis AND preparations:"skull"], [Sciurus carolinensis AND preparations:skull], [Sciurus carolinensis preparations:skull], as well as Advanced searches that use the term "skull" in the fields for "All these words,", Exact phrase," and "Any of these words."

In all cases I was able to return records for S. niger or S. carolinensis with preparations that included the term "skull".  Unfortunately, I also returned records that did not include the term "skull."  In all cases, these additional records did not have "skull" in any field within the record, including dwc:preparations.  They did include things such as "sample skin," "SS, " and "tissue" among other things that should not have been included in query results.

Carla tested this with genus:aplodontia using the same syntax and the same advanced fields.  Her results also returned records with samples skin, tissue, and without skulls.

I realize that dwc:preparations does not use a standardized vocab, but I would expect the search API to return the correct records based on keyword searching.

**Comment by laurarussell** [comment]
Dave can you retest this now that the new index is launched and see if we still have the same issue?

**Comment by laurarussell** [comment]
Preparations added as field to advanced search options.

**Comment by laurarussell** [comment]
Fixed by #563
