### ISSUE TITLE
search API error handling

### ISSUE THREAD

**Issue by stuckyb** [VertNet/webapp#437]
A variety of malformed queries to the search API trigger "Internal Server Error" responses with Python call stack dumps.  We should detect these errors properly and provide meaningful error messages.  Examples are running a query with no "q" property, not providing a "q" GET argument, etc.

**Comment by tucotuco** [comment]
I believe this to be covered by major changes in f46c5fd790d9b3ecfbd08f6be2ad7ebb6bb9af7b.
