### ISSUE TITLE
API feedback function documentation

### ISSUE THREAD

**Issue by stuckyb** [VertNet/webapp#439]
The documentation of the API feedback function is, I think, quite confusing.  It includes virtually no explanation of the API interface beyond a chunk of Python code with almost no documentation or inline comments.

To further add to the confusion, the code appears to rely on a property called "keyname" that, as far as I can tell, is not even included in results from the API search function.

**Comment by laurarussell** [comment]
@stuckyb rewrote the API documentation (or is this within the API code).  Is this still an open issue?

**Comment by tucotuco** [comment]
Also checked and updated the API documentation. Closing.
