### ISSUE TITLE
Download creates folder instead of file

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#484]
From API (not sure about from portal)...

Results of queries are somehow written to a folder rather than a file.

Examples:

You can download "myresults" here within the next 24 hours:
https://storage.cloud.google.com/vn-downloads/myresults-c91d52946a164d4995b280ef687997bf.txt

You can download "tucodownloadtest" here within the next 24 hours: https://storage.cloud.google.com/vn-downloads/tucodownloadtest-a626bf4f71984ae183a667554e0f9242.txt

**Comment by laurarussell** [comment]
Verify that this issue is resolved.

**Comment by tucotuco** [comment]
Resolved in major Files API deprecation overhaul (f46c5fd790d9b3ecfbd08f6be2ad7ebb6bb9af7b).
