### ISSUE TITLE
CartoDB.js throws error

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#489]
Version of CartoDB in use currently (2.0.48) throws error:

Uncaught ReferenceError: reqwest is not defined 

at cartodb.js line 12. See about upgrading CartoDB.

**Comment by laurarussell** [comment]
Is this still an open issue?

**Comment by tucotuco** [comment]
Don't know what this refers to, but note that homemap.heml and github.py are referencing an old version of CartoDB.

https://github.com/VertNet/webapp/blob/f46c5fd790d9b3ecfbd08f6be2ad7ebb6bb9af7b/vertnet/service/github.py#L21

https://github.com/VertNet/webapp/blob/3c44df6efe37380b3f98795f941e03626790651d/www/js/app/views/homemap.js#L52

**Comment by tucotuco** [comment]
Almost certainly no longer and issue. Addressed in commit 578cef5aeaf0d31cf496e39148ad22859589097a.
