### ISSUE TITLE
Link out to description of Quality checks

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#490]
Add a link to a Wiki page on the Quality Tests shown in the Quality tab of the record detail.

**Comment by laurarussell** [comment]
The spatial quality tab includes info buttons and at the bottom links to our Spatial Quality guide,  http://vertnet.org/resources/spatialqualitytabguide.html.  @tucotuco where were you wanting the wiki link, somewhere on the tab or on the guide or is how we've done it sufficient?  The guide was created in Sept 2014, so probably created in relation to this task.

**Comment by tucotuco** [comment]
Looks good.
