### ISSUE TITLE
Quality sanity check

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#491]
What should be the results of the Quality check for the following specimen?

http://tuco.vertnet-portal.appspot.com/o/mvz/mvzherps?id=67615

**Comment by laurarussell** [comment]
What does this mean?  Is this still to be considered open?

**Comment by tucotuco** [comment]
I see no issue with the data quality results for this specimen, now accessible at the following URL.

http://portal.vertnet.org/o/mvz/amphibian-and-reptile-specimens?id=67615
