### ISSUE TITLE
Promote FossilSpecimen usage by providers

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#494]
We're set to query on fossils through the portal. The indexer can currently detect fossils if basisOfRecord contains "fossil" or if the resource code contains "paleo" or "palaeo". That isn't enough to get all fossils. Some collections (UMZC) have fossils mixed in with everything else. Need to see if these can be known from the source data and the basisOfRecord set in the migrator. Basically, check them all and do what needs to be done to fag fossils so they can be found in the portal. 
More discussion, including a list of resources with fossils given in https://github.com/VertNet/webapp/issues/475.

**Comment by laurarussell** [comment]
Was this ever completed?

**Comment by dbloom** [comment]
Yes.
