### ISSUE TITLE
Download size limit and notificiation

### ISSUE THREAD

**Issue by robgur** [VertNet/webapp#505]
Do initial check on the count of records to be downloaded - note that this is not always accurate according to Brian's docs but up to 250K, it was _often_ accurate.  If that count exceeds 250K, do not run the download request but return a notification that this download is too large for VertNet to handle easily and that the requestor should contact <SOMEONE> at VertNet to help with getting results from this query.

250K is somewhat arbitrary.  500K seems large (1/26 of our total record set) and 100K seems rather small (to me).  So it seemed big enough to be big but small enough not choke VN with huge downloads.

**Comment by tucotuco** [comment]
With the refactor from the old Files API to the GoogleCloudStorageLineInputReader, the new limit was set to over 1M records, with a notification if that was insufficient.
