### ISSUE TITLE
Edit coding for Record Type

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#509]
Edit coding for Record Type to support new coding for record type flags in dwc-indexer. See https://github.com/VertNet/dwc-indexer/issues/26

Review following code for potential changes:
https://github.com/VertNet/webapp/blob/master/www/js/app/views/search.js#L443

https://github.com/VertNet/webapp/blob/master/www/js/app/views/search.html#L129

**Comment by tucotuco** [comment]
The original idea behind type was to give the user an easy way to distinguish specimens from observations. The post-harvest processor and index now contain the field vntype, which contains one of 'specimen', 'observation', or 'indeterminate'. These three values are disjunct. Hence, the UI can be much simplified to include just the drop-down box with two values in it, 'specimen' and 'observation' (both lower case) and have query simply add vntype:specimen, for example. The existing value 'Specimen or Observation' is superfluous. If one really wanted this option, then one should leave vntype out of the query conditions.
See vn_type() in vn_utils.py. https://github.com/VertNet/post-harvest-processor/blob/master/lib/vn_utils.py#L1082
```
    if rec.has_key('basisofrecord') == False or len(rec['basisofrecord']) == 0:
        if rec.has_key('dctype') == False or len(rec['dctype']) == 0:
            return 'indeterminate'
        elif 'object' in rec['dctype'].lower():
            return 'specimen'
        return 'observation'
    elif 'obs' in rec['basisofrecord'].lower():
        return 'observation'
    return 'specimen'
```

**Comment by laurarussell** [comment]
addressed in https://github.com/VertNet/webapp/commit/bdbfbed6531346eb87c448760fb49fe158b8479f by updating record type dropdown and adding new basisofrecord dropdown in Darwn Core terms section of Advanced Search.
