### ISSUE TITLE
Remove OSUM Birds from IPTstrays

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#514]
OSUM updated their archives. Once a successful harvest has been conducted, remove the temporary resource on IPTstrays (http://ipt.vertnet.org:8080/iptstrays/resource.do?r=osum-birds).

**Comment by laurarussell** [comment]
Should this be move to Tasks repo?

**Comment by tucotuco** [comment]
Moved to https://github.com/VertNet/Tasks/issues/382.
