### ISSUE TITLE
Arctos records with multiple occurrence events not displaying in the portal

### ISSUE THREAD

**Issue by ccicero** [VertNet/webapp#518]
If an Arctos record has multiple occurrence events, only one shows in the portal, but there are two records in Big Query (example: MSB:Mamm:263731).  

From Laura: I've copied a portion of the two records from the Big Query July dump of all of the data below.  So the data is there, just not showing in the portal.  My guess is that the portal is somehow grouping on our keyname field that is applied during harvest/indexing which for these records would be seen as a dup (John??).

Term	Value
Rank	4
HarvestID	ab4d6055-fac0-43c5-898e-b61a25e4dd1e
Networks	MaNIS,VertNet
Keyname	msb/msbmammals/263731
Icode	MSB

This is the line of code from the ipt_view that Dusty built. This builds the number you see in the ID field below.  

'urn:occurrence:Arctos:' || GUID || ':' || specimen_event.specimen_event_id occurrenceID

Perhaps specimen_event_id is not what the user sees in Arctos?

Row	institutioncode	collectioncode	catalognumber	id	eventdate	eventremarks	 
1	MSB	MSB Mammals	263731	urn:occurrence:Arctos:MSB:Mamm:263731:1941369	2004-03-22	associated with NK 108102	 
2	MSB	MSB Mammals	263731	urn:occurrence:Arctos:MSB:Mamm:263731:1941368	2008-06-05	associated with NK 216094 and accession 2011.071

Keep in mind that this data in the Portal for MSB is from July 13.  Still working on getting everything republished.  Likely will have everything moved to the new server on Friday and republished over the weekend.

**Comment by laurarussell** [comment]
This is still an issue. @tucotuco ideas for resolving?

**Comment by tucotuco** [comment]
Fixed in post-harvest-processor in 199ce7398ab2890ada701f712a7e6b6db4b431ae
