### ISSUE TITLE
Select 1+ & search from a full list of collections in Vertnet

### ISSUE THREAD

**Issue by mkoo** [VertNet/webapp#522]
Sorely missed from previous MaNIS portal (this is from Patton): ability to search more than one collection from a dropdown of all the collections in the portal. This is valuable for users to see all the collections online since not everyone knows museum acronyms nor what publishers are in the portal from the advanced search page. Searching on more than one institution is also not obvious since there is field for instiution code and 'Any of these words' does not look like a field for institution codes.

**Comment by tucotuco** [comment]
Searching on multiple institutions is supported via URL and API, but not via the UI directly, as it supports the selection of a single Institution, now from a list. It is unclear that the coding effort and the resulting clutter on the UI would be worth it.

**Comment by laurarussell** [comment]
I did experiment with this as we were making the traits changes and to make a multi-select, completely changes the drop-down and the amount of space required to do it in the UI in addition to adding quite a bit more code in search.js.  I would agree that we shouldn't do this and instead should include documentation on how to search multiple institutions via the API or URL.

**Comment by tucotuco** [comment]
Confirmed. Closing.
