### ISSUE TITLE
Rights page in detail - Source URL

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#523]
Right now this points to the url in the CartoDB resource table. It should point to the source_url field. This should be possible with the new index and harvester changes to propagate the following fields:

icode 
title 
citation 
contact 
dwca 
email
eml
emlrights 
gbifdatasetid 
gbifpublisherid 
lastindexed 
license
migrator 
networks 
orgcountry 
orgname 
orgstateprovince
pubdate
source_url 
url

**Comment by laurarussell** [comment]
URL now using source_url on the Rights tab.

**Comment by laurarussell** [comment]
URL does not open in a new window.

**Comment by laurarussell** [comment]
Fixed so URLs on Rights tabs open in new window/tab.

**Comment by laurarussell** [comment]
Fixed by #563  and #575
