### ISSUE TITLE
Add Month to DwC terms in Advanced Search

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#525]
...So that users can filter by month when conducting a query.

Month uses a standardized vocab, 1=Jan, etc... thus the example in the field should be a number.

**Comment by dbloom** [comment]
An additional comment for a user on searching by month,

"We're looking for earliest (in the spring) and latest (fall) records of hibernating mammals."

**Comment by dbloom** [comment]
Another request for month to be added to the advanced search options:

Hi, David, Laura et al.:

I'm looking for breeding records of some species, and it sure would be nice to filter by month.  I see where I can search by "eventdate", but to use that I'd need wildcard capability, and I can't find if that's possible, or what I should use (I tried standard MySQL wildcards with no success).

Any help would be great.

Thanks,

**Comment by tucotuco** [comment]
Functionality added. UI needs to be updated and Search API documented in wiki. The following fields can be searched now:

 doc_id
 rank
iptrecordid
institutioncode
collectioncode
catalognumber
gbifdatasetid
gbifpublisherid
networks
lastindexed
license
iptlicense
migrator
dctype
basisofrecord
type
continent
country
stateprovince
county
municipality
island
islandgroup
waterbody
locality
geodeticdatum
georeferencedby
georeferenceverificationstatus
kingdom
phylum
class
order
family
genus
specificepithet
infraspecificepithet
scientificname
vernacularname
typestatus
recordedby
recordnumber
fieldnumber
bed
formation
group
member
sex
lifestage
preparations
reproductivecondition
media
tissue
fossil
hastypestatus
wascaptive
haslicense
hashid
verbatim_record
location
mappable
coordinateuncertaintyinmeters
year
month
day
eventdate

**Comment by laurarussell** [comment]
Need to add month to UI.

**Comment by laurarussell** [comment]
Remove Days from UI.

**Comment by laurarussell** [comment]
Fixed by #563 and #574
