### ISSUE TITLE
rank parameter

### ISSUE THREAD

**Issue by sckott** [VertNet/webapp#529]
Docs for `rank` right now on the wiki just say TBD https://github.com/VertNet/webapp/wiki/The-API-search-function

Are there any further details on that param available?

**Comment by tucotuco** [comment]
I amended the docs to say the following:

Rank (code to rank records can be found at https://github.com/VertNet/dwc-indexer/blob/master/utils.py#L197; basically, the most complete records with respect to georeferences, scientific name, and year are rank before all others and appear first in any list)
