### ISSUE TITLE
MaNIS Web Site

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#530]
Update to be reflect current VertNet.

**Comment by laurarussell** [comment]
Need more detail about what this means.

**Comment by tucotuco** [comment]
Wow, poorly presented to begin with.  This one means that the MaNIS web site ought to be updated to say that VertNet is the place to go, and to check for any other out of date information and broken links.

**Comment by tucotuco** [comment]
The MaNIS web site is no longer functional. Content has been archived on georeferencing.org.
