### ISSUE TITLE
API search on occurrenceID fails

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#531]
The accepted structure of an API search based on an occurrenceID is of the form shown in the following example:

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22occurrenceid:7108667e-1483-4d04-b204-6a44a73a5219%22}

Parsing of this format fails for occurrenceIDs that have a ':' in the content, as that is used as a keyword designator. For example, 

http://api.vertnet-portal.appspot.com/api/search?q={%22q%22:%22occurrenceid:urn:catalog:CRCM:Mammals:13-127%22}

**Comment by sckott** [comment]
looking forward to this fix :smile:  Any idea what proportion of occurrence ids have this problem?

**Comment by sckott** [comment]
any update on this?

**Comment by tucotuco** [comment]
The current index has occurrenceIDs in the iptrecordid field. I'm having one of those, "What was I thinking moments." I think it is because this is where the occurrenceID HAD to go in earlier versions of the IPT. In any case, that is where they are, and they can be queried using a pattern that escape quotes the exact string you want to match. For example,

http://api.vertnet-portal.appspot.com/api/search?q={"q":"iptrecordid:\"urn:occurrence:Arctos:CUMV:Amph:10008:2243441\""}

I have updated the API documentation to explain this.

**Comment by sckott** [comment]
great, thanks
