### ISSUE TITLE
Generate KML for download in portal

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#535]
I've received 4 requests for KML files from the portal in the last month.  This appears to be people who used HerpNET previously.  I have been referring them to an external resource.  How difficult is it to provide users with a KML option for download?  Can it be accomplished before the end of the summer?

**Comment by robgur** [comment]
Its trivial in one sense --- there are lots of existing apps that convert
latlon data and associate content into KML.  Can we discuss before we do,
though?  Just briefly?

**Comment by tucotuco** [comment]
Dev call today? Important, as this is an indexing issue.

**Comment by robgur** [comment]
Yes, lets.  We can use the time...

**Comment by dbloom** [comment]
I'll start the call per usual.

**Comment by laurarussell** [comment]
Closing as this is marked wontfix.
