### ISSUE TITLE
Search by institution location

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#537]
A recent user comment/question wondered if it was possible to search for records based on the location of the host institution.  This reminded me that this is the not the first time this request, or one similar to it, has been sent to us.

Thus, can we have a filtering option to look for records based on the location of the institution - perhap by country or state/province?

Not a high priority, but noted for future dev.

**Comment by tucotuco** [comment]
This will require a change to the index schema and a full re-indexing (changes to the gulo), but it is possible. The value to include would be orgcountry from the ipt metadata. We already have that in the CartoDB table.

**Comment by tucotuco** [comment]
Added orgcountry and orgstateprovince to indexing in commit https://github.com/VertNet/dwc-indexer/commit/d4c945450fa94a2fc144dc78b9acae0ff6d6064c.  Consider adding this to the UI.

**Comment by tucotuco** [comment]
I think it should be sufficient to have this enabled via URL and API without cluttering and confusing the UI.

**Comment by laurarussell** [comment]
I agree.  Would require additional documentation (maybe an example on additional fields that can be searched via the URL or API).

**Comment by tucotuco** [comment]
OK, adding Documentation label and reassigning to Dave.

**Comment by dbloom** [comment]
Would this be best added to an existing help page, such as the Advanced Search or Syntax pages (which are both kind long already).  Or would be it be best suited for a "page" of it's own, such as a Portal FAQ entry (http://vertnet.org/resources/help.html#t-tab3) ?  I lean toward the latter.

I think I can use this search for genus:covus orgcountry:australia as an example.
http://portal.vertnet.org/search?q=orgcountry:Australia+genus:corvus

There are corvus in this data set from all around the world, but all are held in collections within AUS.

**Comment by tucotuco** [comment]
I support your proposal to add a Portal FAQ entry,

**Comment by tucotuco** [comment]
This works and is documented at https://github.com/VertNet/webapp/issues/537
