### ISSUE TITLE
Query_log is becoming too large, partitioning suggested

### ISSUE THREAD

**Issue by jotegui** [VertNet/webapp#540]
Query_log stopped logging queries after 2015-03-31T09:44:03Z. Table has now **124.269 rows**, and all attempts to INSERT new rows fail miserably:

```json
{"error": [
  "Your query was not able to finish. Either you have too many queries running or the one you are trying to run is too expensive. Try again."
]}
```

It might be the right time to start re-thinking the structure of this service. A good solution, and not too hard to implement, would be to shift to a partitioned table schema. I have done a similar work recently for MOL and I don't foresee any special issue on this.

**Comment by jotegui** [comment]
Labelling as "priority" since the stats page and the usage reports depend on this table and, so far, there is NO DATA for April usage...

**Comment by robgur** [comment]
Agree.  Priority fix.  Thanks for looking into this and hope we can make
the change ASAP?

**Comment by jotegui** [comment]
A new set of partitioned tables has been created. `query_log_master` is the master table, and there's a partition for each year, starting with `query_log_2013` and ending with `query_log_2016`. A function `query_log_insert_function` redirects each `INSERT` to its proper partition based on the content of the `created_at` field, and the trigger `query_log_insert_trigger` executes this function each time `query_log_master` receives an `INSERT` query. Also, the new set of tables is "cartodbfied", meaning it is accessible via the CartoDB UI and has all CartoDB-specific indexes and triggers (see [this link](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql) for more info on `CDB_CartodbfyTable` function).

I have created tables for queries happening in 2013, 2014, 2015 and 2016. This last one gives us time between now and the end of 2016 to update the set so that it includes a new table and a new rule.

I will post the SQL functions and instructions for updating shortly in a github repo.

**Tasks left: ensure all calls to `query_log` point to `query_log_master`**

**Comment by jotegui** [comment]
SQL functions as well as documentation: https://github.com/jotegui/vn-query-log-partitioning
