### ISSUE TITLE
Ensure all calls to query_log table now point to query_log_master

### ISSUE THREAD

**Issue by jotegui** [VertNet/webapp#542]
Needed extra step related to https://github.com/VertNet/webapp/issues/540

New table `query_log_master` is ready to receive `INSERT` queries and redirect them to the proper partition. We need to  make sure that, in the end, no query is being sent to `query_log` table, since this table should disappear.

I can modify calls from the stats page and regular searches. @tucotuco can you do the same for API calls?

**Comment by jotegui** [comment]
Stats point to daily_portal_stats, which is generated daily from query_log_master

**Comment by robgur** [comment]
So are we back and live on stats?
-r

**Comment by jotegui** [comment]
Gotta do a couple tests to make sure it works properly, but I'd say we are
:)

**Comment by jotegui** [comment]
Hey @tucotuco, did you re-deploy production portal with this change? Checking the dev console, it looks like usage stats are still going to query_log...

**Comment by tucotuco** [comment]
Redeployed just now to be sure. Please check.

**Comment by jotegui** [comment]
Queries are being logged again :)

Javier Otegui
http://about.me/jotegui
