### ISSUE TITLE
Create a CRON task to extract portal stats daily

### ISSUE THREAD

**Issue by jotegui** [VertNet/webapp#543]

**Comment by jotegui** [comment]
Data will be stored in a new CartoDB table

**Comment by jotegui** [comment]
Prototype already working in stats version, sends stats to daily_portal_stats table in CDB

**Comment by robgur** [comment]
Yessssss!  I would like VN-wide stats to go back live ASAP with the new
version.  ETA?

**Comment by jotegui** [comment]
ETA = 0. It's there now! -- well, it's in
http://stats.vertnet-portal.appspot.com/stats. Takes less than 1sec to load
in my box :)

Javier Otegui
http://about.me/jotegui

**Comment by robgur** [comment]
Super fast for me too on mobile.  Woot!
