### ISSUE TITLE
Ability to limit DwC fields for download

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#548]
A user suggestion for our future conversation and updates to the portal.

'would very much appreciate your help in limiting the data fields I retrieve from a search. I need only museum, catalog number, locality (Country, state, county, locality) and co-ordinates. I spend a great deal of time deleting columns of information I do not need or want. Appreciate knowing how to do something other than "complete record."'

**Comment by tucotuco** [comment]
Responded with the following, which satisfied the user:

"There are no options to set in the portal that will allow you to vary the fields returned in the download, which already consists of the Darwin Core. The Darwin Core has lots of fields. There a re a couple of reasons why we include everything in the download. The first is a practical one. Programming the portal to allow users to vary what they see and download is a task that increases the maintenance of the portal code, and we are trying to minimize that for long-term sustainability. The second one is more "contractual". The data publishers share data records in which there are fields with pertinent information to support downstream use and attribution. We want to make sure that information is propagated with every record when it "leaves our hands". I hope that make sense, even if it isn't satisfying for your ease of use. "

**Comment by tucotuco** [comment]
Responded with the following, which satisfied the user:

"There are no options to set in the portal that will allow you to vary the fields returned in the download, which already consists of the Darwin Core. The Darwin Core has lots of fields. There a re a couple of reasons why we include everything in the download. The first is a practical one. Programming the portal to allow users to vary what they see and download is a task that increases the maintenance of the portal code, and we are trying to minimize that for long-term sustainability. The second one is more "contractual". The data publishers share data records in which there are fields with pertinent information to support downstream use and attribution. We want to make sure that information is propagated with every record when it "leaves our hands". I hope that make sense, even if it isn't satisfying for your ease of use. "
