### ISSUE TITLE
Must login to Google Account to receive downloads

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#551]
Cloud storage seems to have capability (now) for public access so we need to make sure the files are tagged for public accessibility.

Documented instances of this on 2014-06-11 (from Melanie Arnett) and 2014-09-04 (from Dario Zuccon).  See emails for details.

**Comment by laurarussell** [comment]
These links describe the issue/resolution:

https://cloud.google.com/storage/docs/access-public-data

https://cloud.google.com/storage/docs/gsutil/commands/acl

**Comment by laurarussell** [comment]
From: https://cloud.google.com/storage/docs/gsutil/commands/acl

If you want to make an object or bucket publicly readable or writable, it is recommended to use “acl ch”, to avoid accidentally removing OWNER permissions.

Ch

The “acl ch” (or “acl change”) command updates access control lists, similar in spirit to the Linux chmod command. You can specify multiple access grant additions and deletions in a single command run; all changes will be made atomically to each object in turn. For example, if the command requests deleting one grant and adding a different grant, the ACLs being updated will never be left in an intermediate state where one grant has been deleted but the second grant not yet added. Each change specifies a user or group grant to add or delete, and for grant additions, one of R, W, O (for the permission to be granted). A more formal description is provided in a later section; below we provide examples.

Ch Examples

Examples for “ch” sub-command:

Grant anyone on the internet READ access to the object example-object:

gsutil acl ch -u AllUsers:R gs://example-bucket/example-object
NOTE: By default, publicly readable objects are served with a Cache-Control header allowing such objects to be cached for 3600 seconds. If you need to ensure that updates become visible immediately, you should set a Cache-Control header of “Cache-Control:private, max-age=0, no-transform” on such objects. For help doing this, see gsutil help setmeta.

**Comment by laurarussell** [comment]
in download.py code, acl is set to 'public-read' which is good.  Finally found on stackoverflow...t

the url in the email should begin storage.googleapis.com instead of storage.cloud.google.com.

**Comment by tucotuco** [comment]
Fixed in 7337c62ddbb445e218d566842b2e578b092e21c0
