### ISSUE TITLE
Fix non-funtional search link on portal main page

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#555]
The "More search options" link on http://portal.vertnet.org/ is no longer functional.  It should be a hyperlink to http://portal.vertnet.org/search?advanced=1

**Comment by dbloom** [comment]
Consider redirecting portal.vertnet.org to portal.vertnet.org/search.  The 'home page" serves no purpose and there is no reason to maintain it.

**Comment by robgur** [comment]
+1

**Comment by laurarussell** [comment]
Same as #448 also.  Closing it.

**Comment by laurarussell** [comment]
redirect deployed
