### ISSUE TITLE
Search by data set from publisher pages

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#559]
Right now we have a button on each Publisher page to "Search this publisher". Javi suggests, and I agree, that searching by data set is (probably even more) useful. Can we add a "Search this data set" button on the data set rows on the publisher pages?

**Comment by laurarussell** [comment]
I've already included this in the UI changes I'm making. Each data set now have a search button and a view meta data button. Testing coming soon when I'm back from Copenhagen.

**Comment by laurarussell** [comment]
Related to issue #132

**Comment by tucotuco** [comment]
Awesome!!!

**Comment by laurarussell** [comment]
Fixed by #563
