### ISSUE TITLE
Giant searches don't log with apitracker

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#566]
If the INSERT statement to CartoDB is too large to, the apitracker throws an error. We need to consider logging a much smaller key than the url. gbifdatasetid would be smaller and more stable. Does this seem reasonable @jotegui ?

Following is an example that failed for downloading country:Canada.

SQL: INSERT INTO query_log_master(             api_version, client, count, download, downloader, error, lat, lon,             matching_records, query, query_version, request_source, response_records,             results_by_resource, type) VALUES (             'api.py 2015-08-29T13:22:58+02:00', 'portal-prod', 467267, '/vn-downloads2/canadatest.txt-131da9614280479c8d69e8d61415bf5a.tsv', 'gtuco.btuco@gmail.com', 'None', 47.394144, 0.68484,             467267, 'country:Canada', 'search.py 2015-08-29T21:04:44+02:00', 'DownloadAPI', 267,             '{"http://ipt.vertnet.org:8080/iptstrays/resource.do?r=tubri_fish": 53, "http://fmipt.fieldmuseum.org:8080/ipt/resource.do?r=fmnh_fishes": 677, "http://ipt.vertnet.org:8080/ipt/resource.do?r=fhsm_mammals": 60, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=blb_all": 1184, "http://ipt.vertnet.org:8080/ipt/resource.do?r=psm_verts": 2618, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ummz_mammals": 2643, "http://ipt.vertnet.org:8080/ipt/resource.do?r=kstc_schmidt_mammals": 10, "http://ipt.nhm.ku.edu/ipt/resource.do?r=kubi_mammals": 2354, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uam_herp": 50, "http://gbif.rom.on.ca:8180/ipt/resource.do?r=birdspass": 53431, "http://ipt.nhm.ku.edu/ipt/resource.do?r=kubi_ornithology_tissue": 17, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cumv_bird": 1694, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ncsm_fishes": 61, "http://ipt.vertnet.org:8080/ipt/resource.do?r=chas_verts": 121, "http://ipt.vertnet.org:8080/ipt/resource.do?r=fhsm_fish": 11, "http://ipt.vertnet.org:8080/ipt/resource.do?r=amnh_birds": 14279, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uaic_fish": 122, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mlz_bird": 25, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uafmc_mammals": 17, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ummz_herps": 419, "http://ipt.vertnet.org:8080/ipt/resource.do?r=hsu_wildlife_eggs_nests": 74, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mvz_hild": 1, "http://fmipt.fieldmuseum.org:8080/ipt/resource.do?r=fm_birds_eggs": 1239, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cm_birds": 16934, "http://iptsnomnh.cloudapp.net:8080/ipt/resource.do?r=nest": 2, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ubc_bbm_ctc_mammals": 17251, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ncsm_vertpaleo": 25, "http://web.macs.ualberta.ca:8088/ipt/resource?r=uamz_mammalogy": 9061, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=nmnh_fishes": 1977, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=nmnh_birds": 13691, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ncsm_herps": 32, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ummz_birds": 6406, "http://ipt.vertnet.org:8080/ipt/resource.do?r=tnhc_fish": 22, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cumv_rept": 116, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cumv_mamm": 650, "http://ipt.vertnet.org:8080/ipt/resource.do?r=aum_fish": 9, "http://ipt.vertnet.org:8080/ipt/resource.do?r=nysm_birds": 243, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mmnh_birds": 899, "http://phylo.ansp.org:8080/ipt/resource.do?r=ansp_orn": 2453, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ncsm_birds": 22, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mvz_mammal": 6397, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=anwc_all": 39, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uam_mamm": 3557, "http://ipt.vertnet.org:8080/ipt/resource.do?r=crcm_verts": 250, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ncsm_mammals": 14, "http://iptsnomnh.cloudapp.net:8080/ipt/resource.do?r=fish": 5, "http://ipt.vertnet.org:8080/ipt/resource.do?r=isu_mammals": 132, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cm_herps": 647, "http://ipt.vertnet.org:8080/ipt/resource.do?r=msb_mamm": 10135, "http://fmipt.fieldmuseum.org:8080/ipt/resource.do?r=fmnh_herps": 504, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mvzobs_bird": 33, "http://ipt.vertnet.org:8080/ipt/resource.do?r=wfvz_birds": 9328, "http://ipt.peabody.yale.edu/ipt/resource.do?r=ipt_vp": 572, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mlz_mamm": 8, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cumv_fish": 450, "http://fmipt.fieldmuseum.org:8080/ipt/resource.do?r=fmnh_mammals": 1862, "http://www.gbif.se/ipt/resource.do?r=mzlu": 28, "http://gbif.rom.on.ca:8180/ipt/resource.do?r=vpfossils": 4130, "http://ipt.peabody.yale.edu/ipt/resource.do?r=ipt_vz_her": 144, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uwymv_bird": 12, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=am_all": 54, "http://gbif.rom.on.ca:8180/ipt/resource.do?r=birdsnonpass": 33322, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ucm_mammals": 176, "http://ipt.vertnet.org:8080/ipt/resource.do?r=hsu_wildlife_birds": 11, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mvz_bird": 11277, "http://ipt.calacademy.org:8080/ipt/resource.do?r=orn": 2041, "http://ipt.vertnet.org:8080/ipt/resource.do?r=msu_mammals_birds_vertpaleo": 404, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ubc_bbm_ctc_herps": 1259, "http://pontos.fwl.oregonstate.edu:8080/ipt/resource.do?r=oregonstate_fish": 95, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=angelo_mammals": 1, "http://iptsnomnh.cloudapp.net:8080/ipt/resource.do?r=birds": 88, "http://ipt.vertnet.org:8080/ipt/resource.do?r=mvz_herp": 878, "http://ipt.calacademy.org:8080/ipt/resource.do?r=herp": 496, "http://ipt.vertnet.org:8080/ipt/resource.do?r=csuc_verts": 15, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=wam_all": 64, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=nmnh_mammals": 18860, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ucla_birds_mammals": 605, "http://ipt.vertnet.org:8080/ipt/resource.do?r=tnhc_herps": 126, "http://gbif.no/ipt/resource.do?r=o_mammals": 82, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uwfc_fish": 1904, "http://ipt.vertnet.org:8080/ipt/resource.do?r=nysm_mammals": 196, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cumv_amph": 210, "http://ipt.vertnet.org:8080/ipt/resource.do?r=hsu_wildlife_mammals": 54, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ucm_herps": 426, "http://digir.mcz.harvard.edu/ipt/resource.do?r=mcz_subset_for_vertnet": 22157, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uam_es": 281, "http://ipt.vertnet.org:8080/ipt/resource.do?r=dmns_mamm": 44, "http://ipt.vertnet.org:8080/ipt/resource.do?r=isu_birds": 138, "http://ipt.vertnet.org:8080/ipt/resource.do?r=smns_herps": 34, "http://ipt.vertnet.org:8080/ipt/resource.do?r=msum_fish_herps": 38, "http://ipt.vertnet.org:8080/ipt/resource.do?r=msb_bird": 59, "http://ipt.vertnet.org:8080/ipt/resource.do?r=cuml_sound_film": 6234, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=csiro_fish": 4, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=flmnh_birds": 1783, "http://fmipt.fieldmuseum.org:8080/ipt/resource.do?r=fm_birds": 7968, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=bpbm_verts": 1, "http://ipt.peabody.yale.edu/ipt/resource.do?r=ipt_vz_ich": 140, "http://phylo.ansp.org:8080/ipt/resource.do?r=ansp_ich": 449, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uwymv_mamm": 9, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=osum-birds": 579, "http://ipt.flmnh.ufl.edu:8080/ipt/resource.do?r=ichthyology": 335, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=sama_all": 52, "http://ipt.nhm.ku.edu/ipt/resource.do?r=kubi_ichthyology_tissue": 1, "http://ipt.calacademy.org:8080/ipt/resource.do?r=ich": 647, "http://ipt.vertnet.org:8080/ipt/resource.do?r=unr_herps": 17, "http://ipt.peabody.yale.edu/ipt/resource.do?r=ipt_vz_mam": 685, "http://ipt.vertnet.org:8080/ipt/resource.do?r=sdnhm_herps": 174, "http://ipt.vertnet.org:8080/ipt/resource.do?r=uwbm_birds": 2365, "http://ipt.vertnet.org:8080/iptstrays/resource.do?r=osum_mammals": 52, "http://phylo.ansp.org:8080/ipt/resource.do?r=ansp_hrp": 303, "http://web.macs.ualberta.ca:8088/ipt/resource?r=uamz_ornithology": 6291, "http://ipt.vertnet.org:8080/ipt/resource.do?r=umzc_vertebrates": 766, "http://ipt.nhm.ku.edu/ipt/resource.do?r=kubi_vertpaleo": 42, "http://ipt.vertnet.org:8080/ipt/resource.do?r=ttu_mammals": 101, "http://ipt.vertnet.org:...(length 27673)

**Comment by jotegui** [comment]
As long as gbifdatasetid is stable within our registry tables and all
records have the right value in that field, we should be good (I know, I
might be asking too much :p). Besides, transitioning from using the URL to
using gbifdatasetid is quite straightforward.

**Comment by tucotuco** [comment]
In that case, IMPLEMENTED!  See d75476dbfd6c22abedfdb0d664d7a2f424b50265. Please adjust stats to use gbifdatasetid.

**Comment by tucotuco** [comment]
Related to https://github.com/VertNet/webapp/issues/455.  LARGE searches (e.g., country:Canada) do not log in CartoDB even if there is no apitracker error in the App Engine log on execution. Changing from reporting 'url' to reporting 'gbifdatasetid' considerably shortened the length of the results_by_resource field, but it can still be long. Going to test with a LARGE result with few results_by_resource entries.

**Comment by tucotuco** [comment]
Fixed in fe413a63e6ea350296678143f194da877c8f1e51.
