### ISSUE TITLE
Daily portal stats stuck?

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#570]
The daily portal stats seem to be locked at 25 Aug 2015.

**Comment by jotegui** [comment]
Yes, this is something that has been bugging me for some time. I think it
has to do with some quotas or limits on GAE. When I run the stats
generation code from my dev env it works perfectly, but I have not yet
found the way of making it work on production.

Javier Otegui
http://about.me/jotegui

**Comment by jotegui** [comment]
This was solved some time ago... Closing
