### ISSUE TITLE
IsFossil issues

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#580]
I feel like the IsFossil search is being flaky on the portal.  I had several collections where isFossil didn't work and I had to use "FossilSpecimen"  And then a couple with fossils didn't work at all UTEP and MSU with either (so guessing basisOfRecord is not set correctly on those). 

Here are the ones that I tried, you can see which ones didn't work with fossil:1...maybe it is an indexing problem and not a search problem?  If so, may need cross-list an issue in dwc-indexer.

UCMP: http://portal.vertnet.org/search?q=institutioncode:UCMP+fossil:1
Yale: http://portal.vertnet.org/search?q=institutioncode:YPM+fossil:1 (Yale is putting their preps in occurrenceRemarks instead of in preparations)
ROM: http://portal.vertnet.org/search?q=institutioncode:ROM+fossil:1
USNM: http://portal.vertnet.org/search?q=FossilSpecimen+institutioncode:USNM
NCSM: http://portal.vertnet.org/search?q=FossilSpecimen+institutioncode:NCSM

**Comment by tucotuco** [comment]
Fixed in post-harvest-processor in commit 199ce7398ab2890ada701f712a7e6b6db4b431ae
