### ISSUE TITLE
Load More Results... returns user to top of search results

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#581]
When I ask the portal to load more records in a search the screen view returns to the top of the records list, rather than remaining at the point in the records list where I made the request.  E.g., If I'm at record 100 and I click "load more records.." I get shot back to record number one.

Hopefully there is a way to keep the initial display of records working this way, but if not, we should probably revert back to the old method since I could see some potential for frustration here.

Here's a search for you test this within: http://portal.vertnet.org/search?q=preparations:skull

**Comment by laurarussell** [comment]
Addressed by https://github.com/VertNet/webapp/commit/bdbfbed6531346eb87c448760fb49fe158b8479f
