### ISSUE TITLE
Flag new publishers on the publishers page

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#587]
Flag new publishers for 120 days.

**Comment by laurarussell** [comment]
robgur commented a day ago
Like the subject says. We can turn off the highlight after 4 months via cron?
 @tucotuco
  
tucotuco commented 3 hours ago
I think there is a better way. Check the date in the web interface code to see if it is more recent than 4 months. If it is, highlight it. No maintenance necessary.
 @robgur
  
robgur commented 2 hours ago
@laurarussell move this over to webapp.
 @laurarussell
  
laurarussell commented just now
There is no moving of tasks around. So I guess I can copy and paste it all where it belongs.

**Comment by tucotuco** [comment]
I don't think this is an important enhancement to make. One can determine "newness" from the data without having it highlighted by the UI, which to me adds clutter.

**Comment by laurarussell** [comment]
To me, the new publisher isn't the important part anyway, it is the new dataset, but since datasets are a level down, no one would see them flagged anyway.  I don't also don't think we should do this one.

**Comment by tucotuco** [comment]
Agreed and closing.

**Comment by robgur** [comment]
Good by me too.
