### ISSUE TITLE
Missing DwC terms from record detail

### ISSUE THREAD

**Issue by laurarussell** [VertNet/webapp#589]
The following three fields are missing from the detail of an occurrence record in the portal:

type
rights (license)
individualID

**Comment by tucotuco** [comment]
The gulo harvester propagates all of these fields, and they appear in the index. The webapp has not been updated to include these - it still references the obsolete "rights" and "individualID" fields. The cause for the missing "type" field is a mystery.

See https://github.com/VertNet/webapp/blob/master/www/js/app/models/detail.js#L24.

**Comment by tucotuco** [comment]
Last of the fixes implemented in https://github.com/VertNet/webapp/commit/fc969d9d13309aa2e1f782b23b003612c66dc295
