### ISSUE TITLE
Design Trait UI

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#591]
Make a mockup and/or explanation of how to incorporate trait fields (generated post-harvest by the traiter scripts) in the portal user interface.
The idea is to add the following fields to the data store:
*haslength
*haslifestage
*hasmass
*hassex
*lengthinmm
*massing
lengthunitsinferred
massunitsinferred
derivedlifestage
derivedsex

* signifies that a field would be key indexed to support queries. The following fields would appear in record details, api results, and downloads:
lengthinmm
massing
lengthunitsinferred
massunitsinferred
derivedlifestage
derivedsex

**Comment by laurarussell** [comment]
Addressed by https://github.com/VertNet/webapp/commit/3590f5b55a11ab7cca8f901d2440a0226bf4b284 and https://github.com/VertNet/webapp/commit/bdbfbed6531346eb87c448760fb49fe158b8479f and https://github.com/VertNet/webapp/commit/61d96765c2d37aba2c57243620ea18546583fa25 and https://github.com/VertNet/webapp/commit/3bf6895bcc11a653fa520ce6035bd926d1f74814 and https://github.com/VertNet/webapp/commit/fc969d9d13309aa2e1f782b23b003612c66dc295.
