### ISSUE TITLE
"Institution Codes" link in search page is absolute

### ISSUE THREAD

**Issue by jotegui** [VertNet/webapp#595]
https://github.com/VertNet/webapp/blob/master/www/js/app/views/search.html#L26

The rest of the links are relative (except those pointing to vertnet.org), but this is hard-coded (http://vertnet.org/publishers). This link leads to the production portal even if we are on a different version (tuco, stats...) or the dev server. I know it's a minor thing, but it might be good for consistency...

**Comment by laurarussell** [comment]
Addressed by https://github.com/VertNet/webapp/commit/3590f5b55a11ab7cca8f901d2440a0226bf4b284
