### ISSUE TITLE
Update documentation for traits

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#600]
The addition of traits was a major overhaul on the post-harvest-processor, dwc-indexer, and webapp. Update documentation of the portal UI and APIs.

Relevant issues that were solved include:
https://github.com/VertNet/webapp/issues/270
https://github.com/VertNet/webapp/issues/518
https://github.com/VertNet/webapp/issues/533
https://github.com/VertNet/webapp/issues/580 
https://github.com/VertNet/webapp/issues/599?

**Comment by tucotuco** [comment]
Also include the new capability to search on lengthtype, with its drop down box of valid types in the UI.

**Comment by dbloom** [comment]
New Traits Guide is up - http://vertnet.org/resources/traitsguide.html
Syntax page has been updated.
Update of existing Advanced Search is underway and should be up shortly.

Closing this issue to focus on #633
