### ISSUE TITLE
Advanced Query start position on page

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#604]
The very first time opening the recently deployed portal, I went to the Advanced Search using the link on the landing page. The Advanced Search opens aligned to the bottom of the page, so that the top of the page is not visible.  The nice uppie arrow button is there, so it is just a click away, but the page should start at the top, not at the bottom.
The same positioning happens after making a search, getting result below, search area collapses, and a new click on "advanced search options" is made.

**Comment by laurarussell** [comment]
Looks like cursor is placed in All these words box which used to be the first box on the page.  I did not notice this as my monitor displays the whole search form.  I'll figure out how to place the cursor at institutioncode or collectioncode if text box is required to place the cursor.

**Comment by laurarussell** [comment]
Addressed in https://github.com/VertNet/webapp/commit/f3ff9f4355d3cb856da81ac6236615f16795ba05.  Cursor position is not institutionCode dropdown.  Please test.

**Comment by tucotuco** [comment]
Confirmed good.
