### ISSUE TITLE
daysofyear UI

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#605]
As of the most recent deployment, the dayofyear fields are presented as a range that goes from startdayofyear to enddayofyear. This won't work to get ranges except for the very special case of matching exactly the startdayofyear and enddayofyear (e.g., startdayofyear==value entered and enddayofyear==another value entered). That does not allow people to do range queries on either fields through the UI. 
What is needed are ranges for each of the two fields.

**Comment by laurarussell** [comment]
Addressed in https://github.com/VertNet/webapp/commit/f3ff9f4355d3cb856da81ac6236615f16795ba05.  Please test.

**Comment by tucotuco** [comment]
Confirmed good.
