### ISSUE TITLE
Isfossil, hasmedia, hastissue changes

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#607]
The names of the fields were changed in the index to make the boolean field names consistent with the post-harvest processor, BigQuery and the snapshots. They were fossil, tissue, and media.  The UI elements need to build the query based on the new field names.

**Comment by laurarussell** [comment]
Addressed with https://github.com/VertNet/webapp/commit/987f314f08d1b2f2d98772caa1cf3ec5379f112e.  Please test.

**Comment by tucotuco** [comment]
Confirmed good.
