### ISSUE TITLE
Record type query

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#608]
The field name for the concept that distinguishes specimen from observation was called type, but was changed to vntype to distinguish it from the Dublin Core type field everywhere that these data will be seen. As a result, the Record type dropdown needs to build the query based on vntype rather than type, which no longer exists in the index.

**Comment by laurarussell** [comment]
When I looked at this yesterday afternoon/last night in the console, I could only find type. Now I don't see type or vntype.  https://console.cloud.google.com/appengine/search/index/dwc?namespace=index-2014-02-11&project=vertnet-portal&pli=1

**Comment by laurarussell** [comment]
never mind.  Now I'm seeing vntype.  It just was refreshing on the screen when I scrolled to the end.

**Comment by laurarussell** [comment]
Addressed with https://github.com/VertNet/webapp/commit/987f314f08d1b2f2d98772caa1cf3ec5379f112e.  Please test.

**Comment by tucotuco** [comment]
Confirmed good.
