### ISSUE TITLE
Translate 0 to No and 1 to Yes for units inferred

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#609]
In the UI, the lengthUnitsInferred and massUnitsInferred show their literal values (0 or 1) in the data store. For the purposes of the UI only (Record detail All Terms and Record detail Traits), translate these to No and Yes to match aesthetic for the Spatial quality tab.

While in there, change the title of the tab from "Record Detail" to "Record detail" to match the capitalization pattern of the other tabs.

**Comment by tucotuco** [comment]
Also, change the labels  for "LengthUnitsInferred" and "MassUnitsInferred" to something more readable, such as "Are Length Units Inferred?"

**Comment by laurarussell** [comment]
The Record detail tab is not like the other tabs on the detail (where fields are specified and placed ).  The Record detail tab simply displays the name of the field and the value if they has data. There are not labels for these terms.  They appear automatically from the terms being included on detail.js.  To modify this would I believe require writing some functions in detail.js.  There is a translate header in util.py.  Maybe can this be changed there?    Or does something similar to the translate header need to be added to detail.js?  Need more advice before proceeding.

**Comment by dbloom** [comment]
Confirmed to use "Are length units inferred?" and "Are mass units inferred?"

Confirmed to use "Sex From Source" and "LifeStage From Source"

**Comment by laurarussell** [comment]
Labels have been changed and units inferred now display Yes or No as appropriate. Fixed in 

https://github.com/VertNet/webapp/commit/31894e817d720e381242efeb75c32a27b32d94ac

https://github.com/VertNet/webapp/commit/d704435a4c54e10c406b3a88c62e3af396cb3225

https://github.com/VertNet/webapp/commit/f21f45b4a0bb7cd641078eff00e229e2b95ce21e
