### ISSUE TITLE
Add lastindexed to Index tab in record detail

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#610]
Somehow I missed this one originally.

**Comment by laurarussell** [comment]
Having issue with this one.  Have added in both detail.js pages and in detail.html.  Have tried a variety of upper/lowercasing lastindexed, but cannot get the data to appear.  @tucotuco What am I missing?

**Comment by tucotuco** [comment]
Solved in commit bff0cd72d77bfd490cd459a43d5b3a960947f427. The record accessed via _get_rec() in search.py did not propagate the lastindexed field, which is not a part of the verbatim_record. Now it does, and lastindexed shows in the Index tab of the record detail. Closing.
