### ISSUE TITLE
Add links out to stats on Publishers page?

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#615]
Just an idea. Could link to stats in GBIF and or iDigBio too.

**Comment by dbloom** [comment]
A good idea, but will it clutter the U/I with all of these links to other portals?

**Comment by tucotuco** [comment]
I was thinking icons, such as those for media and maps on the results
screen.

**Comment by tucotuco** [comment]
See also Issue #515

**Comment by laurarussell** [comment]
We already have the link to our usage stats on the dataset pages.  I feel like maybe it would be more appropriate to point at GBIF stats from the dataset stats page.  We are already providing links on those pages to the GBIF dataset and the GBIF dataset stats and the GBIF publisher page.  If we want to do anything more with them, I think we should provide links here.  See green gbif links in top right of this page, http://tools-usagestats.vertnet-portal.appspot.com/reports/fda9a8f8-6342-4f73-8c3b-8b79e62afc9d/201607/

**Comment by tucotuco** [comment]
That seems perfectly reasonable. Closing.
