### ISSUE TITLE
Search terms overlap Advanced search button

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#617]
In the main query field, when search terms are many, the terms write on top of the Advanced search options button.  Per discussion, attempt to reduce the length of the search field to avoid this overlap.

Example: https://tuco.vertnet-portal.appspot.com/search?q=order:Rodentia+massing+%3E=+50+massing+%3C=+100+lengthinmm+%3E=+400+lengthinmm+%3C=+500+haslifestage:1+haslength:1

**Comment by laurarussell** [comment]
Fixed with https://github.com/VertNet/webapp/commit/31894e817d720e381242efeb75c32a27b32d94ac.  Not sure if will work on always work on all screen sizes in all browsers. Especially phone or tablet browsers...but our site has not been optimized for those.
