### ISSUE TITLE
Add lengthtype to UI and documentation

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#618]
As soon as the index is populated with the term, add it to the UI as a search term and reflect that in the documentation.

**Comment by tucotuco** [comment]
Added lengthtype to the record detail in commit e7550a802673ff43e350040546f99374ce962ba1. Still need to have it as a UI element in the Advanced query interface. Ideally it would be a select box with the following options, in this order:

total length
standard length
snout-vent length
head-body length
fork length
total length range
standard length range
snout-vent length range
head-body length range
fork length range

**Comment by laurarussell** [comment]
Added lengthtype dropdown to advanced search options with https://github.com/VertNet/webapp/commit/706cb14e25697039f24235d43bc9f52490e543c8.  @tucotuco please test that it works as it should.

**Comment by robgur** [comment]
Looks awesome, Laura!

**Comment by tucotuco** [comment]
Looks very good indeed. Usable already, as lengthtype data are loading as we write. Closing issue.
