### ISSUE TITLE
Multiple download notifications

### ISSUE THREAD

**Issue by tucotuco** [VertNet/webapp#620]
Recently I requested a download for records with country Virginia. Over a period of days I received eight notifications that the results were ready for download. Not all notifications have the same request submitted time stamp. They do all refer to the same file to download and the same count. Each has its own request fulfilled time stamp. The first one was as follows:

Your VertNet download file is now available for a limited time at
https://storage.googleapis.com/vn-downloads2/JRW-Virginia-b321cfb8e4314a7c8206ed53cc972550.tsv.

Query: stateprovince:"Virginia"
Matching records: 244557
Request submitted: 2016-08-09T10:47:03.817070
Request fulfilled: 2016-08-09T17:03:01.461810

the most recent one was as follows:

Your VertNet download file is now available for a limited time at
https://storage.googleapis.com/vn-downloads2/JRW-Virginia-b321cfb8e4314a7c8206ed53cc972550.tsv.

Query: stateprovince:"Virginia"
Matching records: 244557
Request submitted: 2016-08-09T10:47:03.817070
Request fulfilled: 2016-08-09T22:08:42.059300

**Comment by tucotuco** [comment]
Interestingly, this query did not end up in the query_log_master table. It could be that the Carto account having no space did not allow the query to log, which may have caused an exception in the ComposeHandler, which then retried until Carto space was restored and logging resumed. If so, interesting way to notify of Carto space being exhausted!  Testing...

**Comment by jotegui** [comment]
If I'm not wrong, the query logging process is launched as a separate task
in a different task queue and should be independent of the search/download
process (which handles the notification), so I don't think that's the case,
but I might be wrong...

**Comment by tucotuco** [comment]
I believe this is cleaned up as of commit 578cef5aeaf0d31cf496e39148ad22859589097a. Have not observed this behavior again.
