### ISSUE TITLE
Get rid of index date in the portal

### ISSUE THREAD

**Issue by pzermoglio** [VertNet/webapp#647]
In the portal, at the very bottom, there is: 
VertNet © webapp version 2018-04-07T20:20-03:00 index-2013-08-08

The index date would seem confusing as if it was the date in which the last index was done. Could we get rid of it?

**Comment by tucotuco** [comment]
Yes we can. That is for internal debugging purposes and doesn't have to bother sensitive peoples.

**Comment by tucotuco** [comment]
Done in commit e062dddc9845732403cc2233426b27387d677d80.
