### ISSUE TITLE
Copyright checks for images and art

### ISSUE THREAD

**Issue by dbloom** [VertNet/webapp#94]
Please submit a list of source URLs, written permissions, and/or send copies of original photos/screenshots/art (if a VN person created them) to dbloom for any and all images and art used on the site so that they can be confirmed in the public domain or CC.

And while stylish, please, no github cats (even if that last one made me laugh).

**Comment by laurarussell** [comment]
@dbloom was this ever completed?

**Comment by dbloom** [comment]
Completed.
